### ISSUE TITLE
Plan out the model for investment

### ISSUE THREAD

**Issue by chrisleee** [ChrisALee/twitch-stocks#11]
@FalseHonesty 's models: [here](https://gist.github.com/FalseHonesty)

**Comment by FalseHonesty** [comment]
Created all of the schemas.

[StockSchema.json](https://gist.github.com/FalseHonesty/df5fce3f88c7845d55a7b2cb44ab24cf)
[ShareContainer.json](https://gist.github.com/FalseHonesty/eb92494ba3971c7ea4c17936bff7ce30)
[ShareSchema.json](https://gist.github.com/FalseHonesty/f6162a2270fa76a3decd0906087d93ac)
[UserSchema.json](https://gist.github.com/FalseHonesty/bfea46f8cc67f4d3a3d79edca5dbc53a)
