### ISSUE TITLE
Create unit tests for back end

### ISSUE THREAD

**Issue by chrisleee** [ChrisALee/twitch-stocks#34]
This will use [Jest](https://github.com/facebook/jest) and [SuperTest](https://github.com/visionmedia/supertest).

**Comment by jallier** [comment]
- [x] Add testing framework
- [ ] Write tests for all routes and cases
- [ ] Test actual response as well as status code
- [ ] Add promise lib for mongoose to get rid of deprecation warnings
- [ ] Look into mocking? This would be ideal so that the tests aren't dependent on connecting to the db
