### ISSUE TITLE
npm install doesn't install devdependencies

### ISSUE THREAD

**Issue by jamiro24** [ChrisALee/twitch-stocks#36]
Could be just on my end, but I had to run 'npm install --only=dev' to get the dev dependencies to install. Did anyone else run into this?

**Comment by chrisleee** [comment]
If you try doing a `npm config get production` does it return false or true?

**Comment by jamiro24** [comment]
it returns false

**Comment by chrisleee** [comment]
Weird. I haven't been able to reproduce this. Reopen if you run into it again.
